version: '2.3'

networks:
  monitor:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    restart: always
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/rules.yml:/etc/prometheus/rules.yml
    ports:
      - "9090:9090"
    networks:
      - monitor

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    hostname: alertmanager
    restart: always
    volumes:
      - ./config/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - ./config/mail.tmpl:/etc/alertmanager/mail.tmpl
    ports:
      - "9093:9093"
    networks:
      - monitor

  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    restart: always
    volumes:
      - ./config/grafana.ini:/etc/grafana/grafana.ini
    ports:
      - "3000:3000"
    networks:
      - monitor

  node-exporter:
    image: quay.io/prometheus/node-exporter
    container_name: node-exporter
    hostname: node-exporter
    restart: always
    ports:
      - "9100:9100"
    networks:
      - monitor

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    hostname: cadvisor
    privileged: true
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - "18080:8080"
    networks:
      - monitor

  dcgm-exporter:
    image: nvidia/dcgm-exporter:1.7.2
    container_name: dcgm-exporter
    hostname: dcgm-exporter
    restart: always
    privileged: true
    ports:
      - "9400:9400"
    networks:
      - monitor

  sys-alert:
    build:
      context: .
      dockerfile: dockerfile
    image: storage-shshukun:5050/shukunqa-sys-alert
    container_name: shukunqa-sys-alert
    hostname: shukunqa-sys-alert
    privileged: true
    restart: always
    environment:
      - log_path=/opt/log
      - log_file=kern.log,sys.log
      - kern_keywords=error,exception,waring
      - interval_time=60
      - server_ip=10.12.10.201
    volumes:
      - /var/log:/opt/log
    networks:
      - monitor
    command: python sys-alert/scheduler_task.py